// Textos de interfaz en los dos idiomas. Los VALORES de los datos (nombres,
// finalidades, sectores...) siguen en español -- traducirlos es trabajo de
// curaduría aparte, no de esta fase. Ver docs/metodologia.md y docs/bitacora.md.
export const diccionario = {
  es: {
    tituloSitio: "Registro de IA Pública — Perú",
    descripcionSitio:
      "Registro público, versionado y continuo de los sistemas de inteligencia artificial que el Estado peruano compra y despliega.",
    navSistemas: "Sistemas",
    navEntidades: "Entidades",
    navMetodologia: "Metodología",
    navIdioma: "English",
    inicioTitulo: "Sistemas de IA en el Estado peruano",
    inicioIntro:
      "Cada ficha lleva evidencia con fecha de captura. La clasificación de riesgo es propia del proyecto, no oficial. Ver metodología.",
    filtroSector: "Sector",
    filtroRiesgo: "Riesgo",
    filtroConfianza: "Nivel de confianza",
    filtroTodos: "Todos",
    buscarPlaceholder: "Buscar por nombre o entidad…",
    columnaSistema: "Sistema",
    columnaEntidad: "Entidad",
    columnaSector: "Sector",
    columnaRiesgo: "Riesgo",
    columnaConfianza: "Confianza",
    columnaEstado: "Estado",
    sinResultados: "Ningún sistema coincide con estos filtros.",
    panelCumplimientoTitulo: "Cumplimiento frente al reglamento",
    panelCumplimientoDetalle: (c, numeroEntidades) =>
      `${c.cumplidas} de ${c.total} obligaciones cumplidas con evidencia, de ${numeroEntidades} entidades registradas.`,
    panelCumplimientoPlazo: (dias) =>
      dias >= 0
        ? `Faltan ${dias} días para el plazo del 10 de setiembre de 2026.`
        : `El plazo del 10 de setiembre de 2026 ya pasó.`,
    fichaEntidad: "Entidad",
    fichaFinalidad: "Finalidad",
    fichaTecnologias: "Tecnologías utilizadas",
    fichaEstado: "Estado",
    fichaProveedor: "Proveedor",
    fichaVinculo: "Vínculo contractual",
    fichaPresupuesto: "Presupuesto",
    fichaSupervisionHumana: "Supervisión humana declarada",
    fichaRiesgo: "Clasificación de riesgo (propia)",
    fichaEuAiAct: "Mapeo EU AI Act",
    fichaNistAiRmf: "Mapeo NIST AI RMF",
    fichaConfianza: "Nivel de confianza",
    fichaEvidencia: "Evidencia",
    fichaNotas: "Notas",
    fichaSinDato: "No declarado",
    entidadSistemas: "Sistemas de esta entidad",
    entidadObligaciones: "Obligaciones de cumplimiento",
    entidadSinSistemas: "No se detectó ningún sistema de esta entidad todavía.",
    columnaObligacion: "Obligación",
    columnaEstadoObligacion: "Estado",
    columnaFechaLimite: "Fecha límite",
    volverIndice: "← Volver al índice",
    volverEntidad: "← Volver a la entidad",
    piePropia: "Clasificación de riesgo propia del proyecto, no oficial.",
    pieFuente: "Código y datos: ",
    pieDescarga: "Descargar todo el conjunto de datos (JSON)",
    pieLicencia: "Código bajo licencia MIT, datos bajo CC BY-SA 4.0.",
    pieInterfases:
      "Incluye la línea base de Huancapaza Hilasaca, J. E. (2025). Implementación de inteligencia artificial en el Estado peruano: catálogo analítico de aplicaciones. Interfases, (22), 143-158.",
    estados: {
      en_operacion: "En operación",
      piloto: "Piloto",
      contratado_sin_desplegar: "Contratado sin desplegar",
      descontinuado: "Descontinuado",
      indeterminado: "Indeterminado",
    },
    riesgos: {
      alto: "Alto",
      limitado: "Limitado",
      minimo: "Mínimo",
      pendiente_de_clasificar: "Pendiente de clasificar",
    },
    confianzas: {
      confirmado_fuente_oficial: "Confirmado por fuente oficial",
      inferido_contratacion: "Inferido de contratación",
      reportado_prensa: "Reportado por prensa",
    },
    obligacionEstados: {
      cumplido_con_evidencia: "Cumplido con evidencia",
      no_cumplido: "No cumplido",
      no_verificable_desde_fuentes_publicas: "No verificable desde fuentes públicas",
      no_aplica_todavia: "No aplica todavía",
    },
    supervisionHumana: {
      si: "Sí",
      no: "No",
      no_declarado: "No declarado",
    },
  },
  en: {
    tituloSitio: "Public AI Registry — Peru",
    descripcionSitio:
      "A public, versioned, ongoing registry of the artificial intelligence systems the Peruvian State procures and deploys.",
    navSistemas: "Systems",
    navEntidades: "Entities",
    navMetodologia: "Methodology",
    navIdioma: "Español",
    inicioTitulo: "AI systems in the Peruvian State",
    inicioIntro:
      "Every entry carries evidence with a capture date. The risk classification is the project's own, not official. See methodology.",
    filtroSector: "Sector",
    filtroRiesgo: "Risk",
    filtroConfianza: "Confidence level",
    filtroTodos: "All",
    buscarPlaceholder: "Search by name or entity…",
    columnaSistema: "System",
    columnaEntidad: "Entity",
    columnaSector: "Sector",
    columnaRiesgo: "Risk",
    columnaConfianza: "Confidence",
    columnaEstado: "Status",
    sinResultados: "No system matches these filters.",
    panelCumplimientoTitulo: "Compliance with the regulation",
    panelCumplimientoDetalle: (c, numeroEntidades) =>
      `${c.cumplidas} of ${c.total} obligations met with evidence, across ${numeroEntidades} registered entities.`,
    panelCumplimientoPlazo: (dias) =>
      dias >= 0
        ? `${dias} days left until the September 10, 2026 deadline.`
        : `The September 10, 2026 deadline has passed.`,
    fichaEntidad: "Entity",
    fichaFinalidad: "Purpose",
    fichaTecnologias: "Technologies used",
    fichaEstado: "Status",
    fichaProveedor: "Provider",
    fichaVinculo: "Contractual link",
    fichaPresupuesto: "Budget",
    fichaSupervisionHumana: "Declared human oversight",
    fichaRiesgo: "Risk classification (project's own)",
    fichaEuAiAct: "EU AI Act mapping",
    fichaNistAiRmf: "NIST AI RMF mapping",
    fichaConfianza: "Confidence level",
    fichaEvidencia: "Evidence",
    fichaNotas: "Notes",
    fichaSinDato: "Not declared",
    entidadSistemas: "Systems from this entity",
    entidadObligaciones: "Compliance obligations",
    entidadSinSistemas: "No system from this entity has been detected yet.",
    columnaObligacion: "Obligation",
    columnaEstadoObligacion: "Status",
    columnaFechaLimite: "Deadline",
    volverIndice: "← Back to index",
    volverEntidad: "← Back to entity",
    piePropia: "Risk classification is the project's own, not official.",
    pieFuente: "Code and data: ",
    pieDescarga: "Download the full dataset (JSON)",
    pieLicencia: "Code under MIT license, data under CC BY-SA 4.0.",
    pieInterfases:
      "Includes the baseline from Huancapaza Hilasaca, J. E. (2025). Implementación de inteligencia artificial en el Estado peruano: catálogo analítico de aplicaciones. Interfases, (22), 143-158.",
    estados: {
      en_operacion: "In operation",
      piloto: "Pilot",
      contratado_sin_desplegar: "Contracted, not deployed",
      descontinuado: "Discontinued",
      indeterminado: "Undetermined",
    },
    riesgos: {
      alto: "High",
      limitado: "Limited",
      minimo: "Minimal",
      pendiente_de_clasificar: "Pending classification",
    },
    confianzas: {
      confirmado_fuente_oficial: "Confirmed by official source",
      inferido_contratacion: "Inferred from procurement",
      reportado_prensa: "Press-reported",
    },
    obligacionEstados: {
      cumplido_con_evidencia: "Met with evidence",
      no_cumplido: "Not met",
      no_verificable_desde_fuentes_publicas: "Not verifiable from public sources",
      no_aplica_todavia: "Not yet applicable",
    },
    supervisionHumana: {
      si: "Yes",
      no: "No",
      no_declarado: "Not declared",
    },
  },
};

export function t(locale) {
  return diccionario[locale] ?? diccionario.es;
}
